### ISSUE TITLE
Issue on another audio file 

### ISSUE THREAD

**Issue by TeerathChandani** [mosheman5/DNP#4]
I used audio file other than demo.wave for denoising.. But code is throwing error like 

Traceback (most recent call last):
  File "DNP.py", line 91, in <module>
    , save_every=opts.save_every)
  File "DNP.py", line 65, in dnp
    accumulator = utils.Accumulator(target, low_cut, high_cut, nfft, center, residual, sr, bandpass)
  File "/content/DNP/utils.py", line 19, in __init__
    self.stft_noisy = torch_stft(noisy_audio, nfft=nfft, center=center)
  File "/content/DNP/utils.py", line 109, in torch_stft
    stft = librosa.stft(in_numpy, n_fft=nfft, center=center)
  File "/usr/local/lib/python3.6/dist-packages/librosa/core/spectrum.py", line 161, in stft
    util.valid_audio(y)
  File "/usr/local/lib/python3.6/dist-packages/librosa/util/utils.py", line 163, in valid_audio
    'ndim={:d}, shape={}'.format(y.ndim, y.shape))
librosa.util.exceptions.ParameterError: Invalid shape for monophonic audio: ndim=2, shape=(171392, 2) 

Any solution?

**Comment by mosheman5** [comment]
Seems like you tried to use a stereo file, as the model currently supports only single channel.
Changed the code to convert stereo input to mono, please check if the problem is solved.

**Comment by TeerathChandani** [comment]
Okay Thanks.
